# Generated by Django 4.1.7 on 2023-04-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
    ]
